### ISSUE TITLE
bug: Conflicts with RJSONIO

### ISSUE THREAD

**Issue by MansMeg** [jimhester/covr#100]
Package ```covr``` is not working when testing a package that contains RJSONIO.

See: https://travis-ci.org/rOpenGov/pxweb/builds/65754065

````
126.65s$ Rscript -e 'library(covr);coveralls()'
Loading required package: methods
Loading required package: methods
Loading required package: pxweb
pxweb: R tools for PX-WEB API.
Copyright (C) 2014 Mans Magnusson, Leo Lahti, Love Hansson
https://github.com/ropengov/pxweb
Note: the specification for S3 class “AsIs” in package ‘jsonlite’ seems equivalent to one from package ‘RJSONIO’: not turning on duplicate class definitions for this class.
Warning in file(con, "r") :
  cannot open: HTTP status was '404 Not Found'
Execution halted
````

**Comment by brodieG** [comment]
I've had issues using `setOldClass`.  I ran into this a while ago so I don't 100% remember the details, but seems relevant here.  My package defined an old class that RJSONIO also defined.  For whatever reason, it appears that old classes are not namespaced, so this created a conflict.  The only straightforward resolution I found was to simply drop the use of `setOldClass` altogether for fear that I could introduce a conflict with another package.  So my S4 classes use "ANY" for any any S3 slots, and then use validity functions to ensure they are what they are supposed to be.

For reference, the issue was with class "file".  Might also have involved the use of a `setClassUnion`.  This is the code I ended up having to comment out:
```
# setOldClass("file")
# setOldClass(c('package_version', 'numeric_version'))
# setClassUnion("fileOrNULL", c("file", "NULL"))  # removed due to conflicts with RJSONIO
```
Sorry this is kind of vague, but I don't have the time right now to re-run the tests I did back then, but figure this info might be useful.

[old R devel thread that might be relevant](http://r.789695.n4.nabble.com/Same-class-name-different-package-td3684394.html).

**Comment by jimhester** [comment]
Yeah I think it is a jsonlite / RJSONIO incompatibility issue because they are both calling `setOldClass("AsIs")` (https://github.com/jeroenooms/jsonlite/blob/777c721/R/asJSON.AsIs.R#L1, https://github.com/duncantl/RJSONIO/blob/53d6d31/R/readJSON.R#L5)

The message is just a note however, so it can be safely ignored in this case IMHO.

@MansMeg if you are concerned with this you can try to report it at https://github.com/jeroenooms/jsonlite/issues, but I am not really sure what they can do to resolve it.  They could check to see if 'AsIs' already `inherits("oldClass")` before calling `setOldClass()`, but that will only help if RJSONIO is loaded first, not the opposite.
