### ISSUE TITLE
Coverage report incorrect when using parSapply

### ISSUE THREAD

**Issue by csgillespie** [jimhester/covr#139]
The report on one of my functions is almost certainly wrong:

https://codecov.io/github/csgillespie/poweRlaw/pkg/R/bootstrap.R?ref=d88523121f2399ac627a8a6d65d90d2361ffc988#l-33

Since the test completes correctly, it must call lines 36-46. However, coverage stops on line 33, just after the `parSapply` function call.

**Comment by jimhester** [comment]
covr doesn't support parallel code at the moment and I don't really have plans to do so. I am guessing something is going wrong due to how the parallel package sets up and tears down the cluster which breaks assumptions covr makes about the code. But again this feature is in the far future (if at all).

**Comment by jimhester** [comment]
This should now be fixed. Please reopen if that is not the case.
