### ISSUE TITLE
Export results to web server?

### ISSUE THREAD

**Issue by kenahoo** [jimhester/covr#152]
I'm starting to look at `covr` and we'd love to use it in our company.  The shiny app is great for browsing through coverage results.  We'd like to set up our CI server to run coverage metrics and export these to a server for offline browsing - is this something that can already be done in `covr`?  From my quick look through the HTML it doesn't look like any requests to the shiny server are actually made when the user clicks around in the results, so it should work fine standalone.

If not, maybe we could create a method that exports the HTML for static offline browsing?  I'm not familiar with the code yet, but I can work up a pull request if it's not too hard.

**Comment by jimhester** [comment]
The current implementation was born out of convenience rather than necessity.

The only real drawback to using a fully static output is all of the source code would need to be included in the document. The current implementation only needs to load the source of the file being viewed.

Alternatively perhaps you could look into using something like codecov enterprise (https://codecov.io/#pricing) and using the existing codecov support it covr, which would give you much more featureful reporting.

**Comment by kenahoo** [comment]
True, the output could get pretty big with all the source code included, but R packages in general aren't usually very big so it wouldn't be too bad a burden.

An alternative would be to query a REST interface somewhere to get the sources on demand (e.g. from Git), but obviously that would take some implementation and I'm not sure who else would use it.

We haven't looked into commercial coverage reporting yet - I'm still trying to convince people that we'd get some use out of coverage assessments in the first place. =)

**Comment by jimhester** [comment]
I have a WIP for this at https://github.com/jimhester/covr/tree/static_reports which works fine for normal reports, just not for the report seperated by test / example / vignette type.
