### ISSUE TITLE
New error on all packages via travis + covr

### ISSUE THREAD

**Issue by trinker** [jimhester/covr#171]
All packages now get an error on travis-ci as of a few days ago that I can not make heads or tails of:

```
Using bundled GitHub PAT. Please add your own PAT to the env var `GITHUB_PAT`
Downloading GitHub repo jimhester/covr@master
from URL https://api.github.com/repos/jimhester/covr/zipball/master
Installing covr
Using bundled GitHub PAT. Please add your own PAT to the env var `GITHUB_PAT`
Error in switch(x$RemoteType, github = remote("github", host = x$RemoteHost,  : 
  EXPR must be a length 1 vector
```

Do you have insight into how to fix this?

Here's the repo travis file: https://github.com/trinker/termco/blob/master/.travis.yml

**Comment by jimhester** [comment]
This actually looks like a devtools issue, but I am as yet not able to replicate it locally. I would also recommend you use the native travis support for R rather than the travis tool as the latter has been largely superseded and if you turn on package caching the native support should be quite a bit quicker for subsequent builds.

**Comment by jimhester** [comment]
I opened https://github.com/hadley/devtools/issues/1165 to track this.
