### ISSUE TITLE
single line function without braces is not detected

### ISSUE THREAD

**Issue by jackwasey** [jimhester/covr#21]
Love this tool, but when I have a single line function without braces, e.g.
```
f <- function(x)
  x
```
the coverage tool neither detects it is covered nor uncovered by tests. (Or at least coveralls.io doesn't display it.)

**Comment by jimhester** [comment]
There are actually two different issues here.

1. single line functions are not counted.
  - This is because single line functions to not have an attached srcref attribute for some reason (possibly a bug in the R parser)
2. lines that contain only a symbol are not counted.
  - I don't really consider this a bug as these lines are either a bug or are part of the body of a function (so they will be counted by the enclosing function).  Plus the lines that you want to be sure are covered are those that actually do something.

I will investigate 1 and see if we can detect this situation and handle it properly, may leave 2 be (but should include it as an exception in the documentation at least).

**Comment by jackwasey** [comment]
Amazingly, quick. Thanks.
