### ISSUE TITLE
Error: In file(con, "r") : cannot open file '<text>': Invalid argument

### ISSUE THREAD

**Issue by HenrikBengtsson** [jimhester/covr#24]
If a package uses tools(*) that "dynamically" create functions based on `eval(parse(text=...))` during build, then such functions will have a `srcfile` attribute that is `"<text>"`.  For example:

```r
> eval(parse(text='foo <- function(...) cat("foo()\n")'))
> attr(attr(foo, "srcref"), "srcfile")
<text>
```

This will cause `covr::coveralls()` to throw an error:
```
> covr::coveralls()
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") : cannot open file '<text>': Invalid argument

6: file(con, "r")
5: FUN(c("<text>")[[1L]], ...)
4: lapply(filenames, readLines)
3: per_line(x)
2: to_coveralls(package_coverage(path, relative_path = TRUE, ...))
1: covr::coveralls()
```

One quick fix is to have `covr::key()` do `gsub("<text>", ".text", ...)` such that they file name, which base on this key, is a valid file name.

Footnotes:
(*) Such tools are `setGenericS3()` and `setMethodS3()` in [R.methodsS3](http://cran.r-project.org/package=R.methodsS3).  Yep, that's my package; I could maybe update those functions to set the `srcfile` attribute such that it points to some kind of source file.  Regardless, there may be other code out there that relies on `eval(parse(text=...))` for creating functions.

**Comment by jimhester** [comment]
Thank you for the detailed description of the issue.  Rather than substituting the filename I think we need to test if `attr(attr(foo, "srcref"), "srcfile")$isFile` is `TRUE` before generating the key.

Also I am not sure how we want to handle reporting coverage of such functions, you can get the lines for the function from `attr(attr(foo, "srcref"), "srcfile")$lines`, so it would be nice to be able to report on the coverage of them as well (in coveralls and interactively).

I will give it some more thought, thanks again for opening the issue

**Comment by jimhester** [comment]
This should be completely fixed now.
