### ISSUE TITLE
covr causes Travis fail only under combination of Mac and R-Devel?

### ISSUE THREAD

**Issue by sfirke** [jimhester/covr#263]
(Sorry if this is not a covr problem, I'm out of my zone here - if so you can just close it)

I have a [Travis build](https://travis-ci.org/sfirke/janitor/builds/229379040) that fails only under 1 combination of R and platform out of 6: Mac OS and R-Devel.

The Travis log has the ERROR starting on line 1872:

> ERROR: dependencies ‘rex’, ‘crayon’ are not available for package ‘covr’
> * removing ‘/Users/travis/R/Library/covr’
> Installation failed: Command failed (1)
> 1.90s$ Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
> missing: dplyr, magrittr, tidyr
> The command "Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
> 

Is that something particular to covr?

**Comment by jamesdunham** [comment]
I just added R-devel + OSX to my build matrix on Travis and see the same failure, only on [OSX R-devel builds](https://travis-ci.org/jamesdunham/dgo/jobs/236964177).

**Comment by ck37** [comment]
I have also run into this for the same reason :/ https://travis-ci.org/ck37/ck37r/jobs/238173717#L1867

**Comment by jdblischak** [comment]
I don't think this is a covr issue. I was receiving the same [error](https://travis-ci.org/jdblischak/workflowr/jobs/248556544), so I [changed my travis settings](https://github.com/jdblischak/workflowr/commit/4a2900e48eb4703526ea2261c085dd6f9a229b7f#diff-354f30a63fb0907d4ad57269548329e3) to only install and run covr on the linux+release build. However the osx+devel build still [failed](https://travis-ci.org/jdblischak/workflowr/jobs/248630818) to install other package dependencies.

```
1.78s$ Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'

missing: callr, rmarkdown, rprojroot, stringr, yaml
```

I couldn't find a good explanation for why some r-devel packages couldn't be installed on macOS. The only thing I could find was this [SO question](https://stackoverflow.com/questions/43968157/skip-certain-combination-of-os-and-version-in-travis-ci). I also posed this [question](https://ropensci.org/blog/2016/07/12/travis-osx#comment-3393479799) on an rOpenSci blog post, but haven't received an answer yet.

Doing some more searching, I found this [Issue](https://github.com/travis-ci/travis-ci/issues/6629) on the travis-ci repos. It confirms that testing with r-devel on osx fails due to package dependencies, but there is not yet an explanation of which packages will fail and why. This problem is clearly affecting lots of R package developers: [GitHub commits about testing r-devel on osx](https://github.com/search?utf8=%E2%9C%93&q=travis+osx+devel&type=Commits)
