### ISSUE TITLE
Using #nocov start/end stops breaks github reports

### ISSUE THREAD

**Issue by elinw** [jimhester/covr#267]
I tried adding `#nocov start` and `#nocov end`  for a bloc of code and while the reports ran locally and on codecov.io perfectly,  the status reporting in github disappeared.

**Comment by jimhester** [comment]
I do not know what you mean, can you link to the repository and build report.

**Comment by elinw** [comment]
https://github.com/ropenscilabs/skimr/pull/101  That's the pull request. If you were to follow the diffs you would see that I started without using #nocov and that gave a confusing report because of the issue of coverage reports not including functions inside lists.   Then I tried adding #nocov inside the list, but that made the report stop showing up in github. Instead of 4 reports (2 from Travis and 2 from codecov.io) I just got 2 (from Travis).

 Then I tried putting it around the whole list, same thing.   This is the code report history https://codecov.io/gh/ropenscilabs/skimr/branch/printconcept which is totally fine.

**Comment by jimhester** [comment]
I don't think the lack of an updated coverage report is due to the `#nocov` lines. If it is this would be a bug in codecov.io, not the covr package all `#nocov` does is omit the lines from the coverage report.

I would not worry about it for now, if you see the behavior again try asking on https://codecov.io/support and see if they can get to the bottom of it.
