### ISSUE TITLE
Errors in tests lead to under-reporting of coverage

### ISSUE THREAD

**Issue by jonclayden** [jimhester/covr#35]
At present, if any of the tests produce an error, `covr` seems to simply silently ignore it, and report coverage without the test in question, or any subsequent ones. It seems like it would be preferable to at least indicate that an error occurred, rather than leaving the user confused as to why the coverage is so low.

**Comment by jimhester** [comment]
Thanks for opening this issue, this was happening because compiled packages have to be tested in a subprocess, and the output was not being passed back to the calling process unless had an error.  Since test failures are not errors this situation was being silently ignored.

Thank you for opening the issue, let me know if you run into any other problems.
