### ISSUE TITLE
Conditional statements (if) reported as covered even if not run

### ISSUE THREAD

**Issue by krlmlr** [jimhester/covr#39]
Why is `do_something()` shown as covered in the following example:

```
if (FALSE)
  do_something();
```

Real-world example: For [the linked file](https://coveralls.io/files/436079701) there is only one test for which I'm pretty sure that `is.matrix(X)` is `TRUE` and `is.complex(X)` is `FALSE`. Also, the function doesn't end prematurely -- however, lines 33, 36 and 38 are indicated as covered.

**Comment by jimhester** [comment]
This is a known issue.  The problem is that an if without a brace
expression is treated as a single statement.

If you change the conditional to

```r
if (FALSE) {
  do_something()
}
```

It should track coverage correctly.

I think it should be possible to code around this case and do the correct
thing in both cases. I just haven't sat down and figured out how.

So in the short term you can do the brace workaround, in the long term I
would like to fix this.

**Comment by krlmlr** [comment]
I have found that an `if` clause is of class `"if"` in the `trace_calls()` function. If you add a test like `else if (inherits(x, "if")) { ... }` somewhere *before* the test for `is.call(x)`, it hits. Probably you knew that already, but if not I hope it helps you finding a solution.

**Comment by krlmlr** [comment]
Now I see your point -- the conditional statement doesn't seem to have a `srcref` attribute, which `trace_calls()` currently relies on.

I have looked at the output of `getParseData(f, includeText = TRUE)` (for a function `f`), it seems useful but I was unable to come up with a working implementation. Looking forward to your solution! I will use more braces until then ;-)
