### ISSUE TITLE
Error in aggregate.data.frame

### ISSUE THREAD

**Issue by piccolbo** [jimhester/covr#57]
This might very well be operator error, but ...

```
ff = function(x) identity(x)
function_coverage("ff", ff(1))
```
Results in 
```
Error in aggregate.data.frame(mf[1L], mf[-1L], FUN = FUN, ...) : 
  no rows to aggregate
```
What am I missing? Thanks

**Comment by jimhester** [comment]
Not at the computer so I can't verify, but I believe function coverage takes the function definition, not the function name.  Remove the quotes in your example and it should work.

**Comment by piccolbo** [comment]
Tried that

```
> function_coverage(ff, ff(1))
Error in get(name, envir = env) : invalid first argument
```

**Comment by jimhester** [comment]
This is a bug related to https://github.com/jimhester/covr/issues/24.  Because the function has no filename `as.data.frame.coverage` works incorrectly.

You can fix the example by pre-pending a filename to the names attribute of the returned coverage.

```r
ff = function(x) identity(x)
cov <- function_coverage("ff", ff(1))
names(cov) <- paste0("<file>", names(cov))
cov

# Package Coverage: 100.00%
# <file>: 100.00%

as.data.frame(cov)
#   filename first_line first_byte last_line last_byte first_column last_column first_parsed last_parsed value
# 1   <file>          1          6         1        28            6          28            1           1     1
```

That being said this is a bug.  Additionally reporting "Package Coverage" from the print method when printing function coverage also makes no sense, we should probably change that to "Overall Coverage" to be general.

**Comment by jimhester** [comment]
Should be fixed with the new srcref based counting.
