### ISSUE TITLE
Coverage of functions in base, stats packages

### ISSUE THREAD

**Issue by RomanTsegelskyi** [jimhester/covr#59]
I am working on a tools for creating test cases for different VM implementations of R and I was thinking if it's possible to measure coverage of functions from default packages with `covr`.

For example, 

```r
function_coverage("colMeans", colSums(UCBAdmissions), env=getNamespace("base"))
```

or 

```r
ctl <- c(4.17,5.58,5.18,6.11,4.50,4.61,5.17,4.53,5.33,5.14)
trt <- c(4.81,4.17,4.41,3.59,5.87,3.83,6.03,4.89,4.32,4.69)
group <- gl(2, 10, 20, labels = c("Ctl","Trt"))
weight <- c(ctl, trt)
lm.D9 <- lm(weight ~ group)
function_coverage("lm", lm(weight ~ group), env=getNamespace("stats"))
```

But now, it seems that `trace_calls` does not insert any trace points into those functions. How can it be changed?

**Comment by jimhester** [comment]
The issue is that `covr` needs a `srcref` attribute in order to trace the calls.  There are two R options which change this behavior.  From `?options`

```
    ‘keep.source’: When ‘TRUE’, the source code for functions (newly
          defined or loaded) is stored internally allowing comments to
          be kept in the right places.  Retrieve the source by printing
          or using ‘deparse(fn, control = "useSource")’.

          The default is ‘interactive()’, i.e., ‘TRUE’ for interactive
          use.

     ‘keep.source.pkgs’: As for ‘keep.source’, used only when packages
          are installed.  Defaults to ‘FALSE’ unless the environment
          variable ‘R_KEEP_PKG_SOURCE’ is set to ‘yes’.
```
If the function you are trying to trace was in a normal package you could just reinstall the package with the `keep.source.pkgs` option to `TRUE`.  However it does not seem possible to re-install base R packages after the initial R installation.

Therefore what I would try is to set the environment variable `R_KEEP_PKG_SOURCE="yes"`, then re-compile R from source.  Then all the functions should have a `srcref` attribute for their calls and everything should work correctly.

Sorry there is not an easier answer to this question :frowning:

**Comment by RomanTsegelskyi** [comment]
Thanks for a good suggestion. This works for default packages, but not for `base` package. Anyway, closing the issue because it's not connected much to `covr`.

**Comment by jimhester** [comment]
I played around a little bit with this today and you can get base functions to have `srcref`s by reloading them from source after the R session is started.  With that you should be able to use covr directly on base functions.

```r
# assumes R subversion source is at "~/R"
lapply(ls(envir=baseenv(), all.names=T), function(x) { unlockBinding(x, env=baseenv()) })
lapply(dir("~/R/src/library/base/R/", full.names=T), source, local=baseenv())
lapply(ls(envir=baseenv(), all.names=T), function(x) { lockBinding(x, env=baseenv()) })

str(base::require)
# function (package, lib.loc = NULL, quietly = FALSE, warn.conflicts = TRUE,
#     character.only = FALSE)
#  - attr(*, "srcref")=Class 'srcref'  atomic [1:8] 583 1 612 1 1 1 583 612
#   .. ..- attr(*, "srcfile")=Classes 'srcfilecopy', 'srcfile' <environment: 0xa5fc4c8>
```

**Comment by RomanTsegelskyi** [comment]
@jimhester thanks a lot
