### ISSUE TITLE
Time for releases?

### ISSUE THREAD

**Issue by piccolbo** [jimhester/covr#63]
Hi,
I am about to release quickcheck 3.1.0. It's a testing package and has covr as an optional dep. For lack of releases, I am pointing my users to commit b181831 because I tested on it, but I am sure you are  not looking forward to bugs being reported referencing a random commit in the past. So if you planned to start doing releases, here is a vote to get that going sooner rather than later. Thanks

**Comment by jimhester** [comment]
@piccolbo what time frame were you hoping to get a quickcheck release?  I can get a covr release done probably sometime this week if that works for you.

**Comment by piccolbo** [comment]
It's already out, no worries, it's in pre-release anyway and as soon as you
do a release, close this issue and I will do a bugfix release and switch to
it.

**Comment by jimhester** [comment]
So one issue with releasing covr is that it uses a currently un-exported function from devtools to call R.  I made a pull request https://github.com/hadley/devtools/pull/699 to export the function which is now merged, but only in the development version.

Because use of un-exported functions generates a NOTE I cannot release covr on CRAN until the next devtools release.

**Comment by piccolbo** [comment]
Thanks

**Comment by jimhester** [comment]
covr 1.0.0 has now been released to CRAN.  Binary packages have not been built yet however, http://cran.rstudio.com/web/packages/covr/index.html
