### ISSUE TITLE
coverage depends on redundant brackets

### ISSUE THREAD

**Issue by piccolbo** [jimhester/covr#65]
You may have mentioned this before but it is quite disturbing that when writing ifs without optional brackets coverage is overestimated. Is this a bug? Thanks

```
> ff
function(x = T) {
    if(x) {
      1}
    else{
      0}
  }
> cov = function_coverage("ff", ff())
> names(cov) <- paste0("<file>", names(cov))
> cov
Package Coverage: 66.67%
<file>: 66.67%
> ff = 
+   function(x = T) {
+     if(x) 
+       1
+     else
+       0
+   }
> cov = function_coverage("ff", ff())
> names(cov) <- paste0("<file>", names(cov))
> cov
Package Coverage: 100.00%
<file>: 100.00%
```

**Comment by jimhester** [comment]
This is the same as #39.  The problem is R considers an `if else` statement without brackets as one entire expression.  There is only one source ref for the entire thing.  As source refs are what we use to determine what expressions to track it causes the issue you observed.

We would have to manually break the expression into parts and insert an artificial srcref for each part to fix this.  

Considering there exists an easy user side fix (just use brackets) I have not spent time handling this case, but as multiple people have reported it I suppose it needs to be done.

**Comment by piccolbo** [comment]
got it. I don't think I would call it a fix, it's a workaround. It seems like the fix is complex. Anyhow, closing this as duplicate.
