### ISSUE TITLE
function_coverage doesn't work with certain ways of creating functions

### ISSUE THREAD

**Issue by piccolbo** [jimhester/covr#74]
This is in the context of package `quickcheck` development. Quickcheck has its own way of creating functions that's based on pryr::f. Surprisingly, `function_coverage` works with the `pryr` function but not with the `quickcheck` one. The function `trace_calls` doesn't seem to instrument the code at all, but I can't understand why

```
library(covr)
library(pryr)
f1 = function(x) {x}
f2 = f(x, {x})
forall = function(...) {do.call(f, dots(...), envir = parent.frame())}
f3 = forall(x, {x})
f1
# function(x) {x}
f2
# function (x) 
# {
#     x
# }
f3
# function (x) 
# {
#     x
# }
unclass(function_coverage("f1", f1(1)))
# $`:1:19:1:19:19:19:1:1`
# [1] 1
unclass(function_coverage("f2", f2(1)))
# $`:1:12:1:12:12:12:1:1`
# [1] 1
unclass(function_coverage("f3", f3(1)))
# list()
```

**Comment by piccolbo** [comment]
OK the difference seems to be an issue of attributes in the body of the function (neither f2 nor f3 have attributes, but body(f2) does)

**Comment by jimhester** [comment]
Right, covr requires calls to have a `srcref` attribute in order to track their coverage, so if the functions created by `quickcheck` do not have `srcref`'s then covr is not going to work.

This is explained in more detail at https://github.com/jimhester/covr/blob/master/vignettes/how_it_works.Rmd#source-references

**Comment by piccolbo** [comment]
Thanks, I was not expecting  dots to zap the srcref, not covr's fault.
