### ISSUE TITLE
covr skips on tests with skip_on_cran?

### ISSUE THREAD

**Issue by karthik** [jimhester/covr#77]
Hi Jim,
I have tests in this repo: https://github.com/karthik/dropr
I have to skip tests on CRAN because there is a encrypted key in the tests folder that can only be decrypted on Travis. But for `covr` it should be able to run tests on Travis and report coverage. But that doesn't appear to be the case. Is covr set to skip all tests if `skip_on_cran` is used?

**Comment by jimhester** [comment]
covr does not set the environment variable `NOT_CRAN=true`, which is what skip_on_cran uses to figure out if the build is running on CRAN. https://github.com/hadley/testthat/blob/0835a9e40d3a2fbaac47cbe8f86239e231623b51/R/utils.r#L61-L65

Because R does not use `devtools::test()` to run the testing code (which is where NOT_CRAN is set) this won't work out of the box.

However you can simply set `NOT_CRAN=true` in your travis.yml and it should work as you expect.

**Comment by karthik** [comment]
Got it. Thanks @jimhester!
