### ISSUE TITLE
slow tests cause travis timeout during coverage check

### ISSUE THREAD

**Issue by jackwasey** [jimhester/covr#78]
Some of my tests unfortunately take a little time, which, on Travis, is amplified to greater than ten minutes resulting in a timeout. I know there are clumsy workarounds in travis for this, but I wondered whether you would consider adding a verbose option which would just let the underlying test framework output whatever it wants to. This would keep travis happy, and let the user choose whether to know how the test coverage check is progressing.

**Comment by jimhester** [comment]
I am guessing the package you are testing uses compiled code.  Unfortunately in this case the tests need to be run on a separate R process, so any test output cannot be communicated back to the original R process until all of the tests are complete.

We could probably have the parent process wait and print the results of the output file periodically rather than blocking, but it will be a little tricky to get right (and is not implemented right now).

**Comment by jackwasey** [comment]
yep, you're right... Is there is no way of listening to the output of the child process and passing that through to the user/travis output?

**Comment by jimhester** [comment]
FYI the changes from https://github.com/jimhester/covr/commit/39530b3a02e2f23135ebcf815a291efaaed4d8d4 should now allow you to have interactive updates even with the compiled code.

However if you are using the devel branch of testthat the default reporter for `test_check` is the `checkReporter` which does not produce interactive output.

If this is the case you simply need to supply a different default reporter i.e.

```r
test_check(pkg, reporter = "summary")
```

Let me know if you still have issues with this.

**Comment by jackwasey** [comment]
Works perfectly, with the added benefit of having the testthat output in the travis log.
