### ISSUE TITLE
Update travis instructions

### ISSUE THREAD

**Issue by hadley** [jimhester/covr#91]
I think it should now be:

```yaml
after_success:
  - Rscript -e 'library(covr);codecov()'
```

+ add covr to package suggests (that's a minor abuse, but it'll give you a better feel for how many people are using it, and will make future revdep checking easier)

Also could it just be Rscript -e 'covr::codecov()' ?

**Comment by jimhester** [comment]
Are you talking about for [`devtools::use_coveralls()`](https://github.com/hadley/devtools/blob/master/R/infrastructure.R#L176-L204) or for the README here?   I put the codecov section above the coveralls section to promote it more in the covr README.

If you are referring to `use_coveralls()` we should either add a `use_codecov()` function or just rename it to `use_coverage()` and have it point to codecov by default.

I can track it fairly well by searching for yaml results for [jimhester/covr](https://github.com/search?l=yaml&p=33&q=jimhester%2Fcovr&ref=searchresults&type=Code&utf8=%E2%9C%93).  Although now that it is on CRAN that may become more problematic.  I fear the ship has already sailed in getting people to put it in Suggests.

I initially used `covr::codecov()` but was running into an error due to the methods package not being attached from devtools, which is why I switched to loading the package explicitly.  I think that issue is fixed however at https://github.com/hadley/devtools/pull/696, so we can switch back.
